##
# This file is part of the ChillDev-Parent.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2015 - 2016 © by Rafal Wrzeszcz - Wrzasq.pl.
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

language: "java"

sudo: false

jdk:
    - "oraclejdk8"

install: true

script: "mvn verify site"

after_script: "mvn coveralls:report"

notifications:
    webhooks:
        urls:
            - "https://webhooks.gitter.im/e/42cfb538d50215e50977"
